import { Presentation, PresentationFile, row, column, grid, text, image, rule, fill, fixed, wrap, grow, fr } from "../qa/artifact_workspace/node_modules/@oai/artifact-tool/dist/artifact_tool.mjs";
import { readFileSync, mkdirSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const manifest=path.join(ROOT,"deliverables","04_presentation","assets","gta_examples","gta_example_manifest.json");
const cases=JSON.parse(readFileSync(manifest,"utf8"));
const deck=Presentation.create({slideSize:{width:1920,height:1080}});
const C={ink:"#3D2A87",muted:"#5D716C",paper:"#F3F2F0",green:"#147D72",lime:"#11B8B5",ochre:"#F2C94C",red:"#EC3F6B",white:"#FFFFFF",pale:"#E8E5F3",teal:"#11B8B5",pink:"#EC3F6B",yellow:"#FFE266",purple:"#3D2A87"};
const FONT="Arial"; const base={fontFamily:FONT,color:C.ink};
const title={...base,fontSize:40,bold:true}; const sub={...base,fontSize:23,color:C.muted}; const label={...base,fontSize:20,color:C.muted}; const value={...base,fontSize:22,bold:true};
const fmt=(v,d=2)=>Number(v??0).toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d}); const ha=v=>`${fmt(v)} ha`;
const car2=s=>`${s.slice(0,24)}\n${s.slice(24)}`;
const dataUrl=p=>`data:image/png;base64,${readFileSync(p).toString("base64")}`;
const niceSource=s=>s==="simcar_validado"?"SIMCAR Validated":s==="simcar_digital"?"SIMCAR Digital":"SIMCAR Proxy";
const isLarge=c=>Number(c.MODULOS_FI)>4;
function footer(page){return row({width:fill,height:fixed(44),justify:"between",align:"center"},[text("Source: final GTA compliance mega table",{width:wrap(1400),height:fixed(34),style:{...label,fontSize:20}}),text(String(page).padStart(2,"0"),{width:fixed(70),height:fixed(34),style:{...label,fontSize:20,bold:true,color:C.green,textAlign:"right"}})]);}
function heading(t,s,p){return column({width:fill,height:fixed(104),gap:3},[text(t,{name:`title-${p}`,width:fill,height:fixed(52),style:{...title,fontSize:40,color:C.purple}}),text(s,{width:wrap(1700),height:fixed(35),style:{...sub,fontSize:20}}),rule({width:fixed(110),stroke:p%2?C.teal:C.pink,weight:6})]);}
function rows(items,accent){return column({width:fill,height:fill,gap:0},items.map((r,i)=>row({width:fill,height:grow(1),align:"center",padding:{x:16,y:7},style:{fill:i%2?C.paper:"#FBFAF6"}},[text(r[0],{width:grow(1.35),height:fixed(30),style:label}),text(r[1],{width:grow(1),height:fixed(32),style:{...value,color:r[2]||accent,textAlign:"right"}})])));}
function tableRow(cells,header=false,index=0){const widths=[.9,.7,2.1,1.65];return row({width:fill,height:header?fixed(58):grow(1),align:"center",padding:{x:18,y:10},gap:14,style:{fill:index%2?"#FFFFFF":"#EEEAF7"}},cells.map((cell,i)=>text(cell,{width:grow(widths[i]),height:header?fixed(34):fixed(58),style:{...base,fontSize:20,bold:header||i===0,color:header?C.purple:(i===1?C.green:C.ink)}})));}
function summaryRow(cells,header=false,index=0){const widths=[.85,.65,1.8,.9,1.15];return row({width:fill,height:header?fixed(58):grow(1),align:"center",padding:{x:18,y:10},gap:14,style:{fill:index%2?"#FFFFFF":"#EEEAF7"}},cells.map((cell,i)=>text(cell,{width:grow(widths[i]),height:header?fixed(34):fixed(58),style:{...base,fontSize:20,bold:header||i===0,color:header?C.purple:(i===4?C.green:C.ink),textAlign:i>=3?"right":"left"}})));}
function formula(name,expression,result,accent){return column({width:fill,height:grow(1),gap:8,padding:{x:24,y:16},style:{fill:"#FBFAF6"}},[text(name,{width:fill,height:fixed(30),style:{...label,fontSize:20,bold:true,color:accent}}),text(expression,{width:fill,height:fixed(54),style:{...base,fontSize:20}}),text(`= ${result}`,{width:fill,height:fixed(38),style:{...value,fontSize:24,color:accent}})]);}

// Cover — image-led split inspired by the supplied fluid-shapes template.
{const s=deck.slides.add();s.compose(row({width:fill,height:fill,style:{fill:C.paper}},[column({width:fixed(950),height:fill,padding:{x:90,y:78},gap:25,style:{fill:C.paper}},[text("FOREST CODE · GTA-LINKED WORKED EXAMPLES",{width:fill,height:fixed(42),style:{fontFamily:FONT,fontSize:20,bold:true,color:C.pink,letterSpacing:1.4}}),text("Six properties.\nThree source bases.\nEvery vector layer visible.",{width:fill,height:fixed(330),style:{fontFamily:FONT,fontSize:40,bold:true,color:C.purple}}),rule({width:fixed(260),stroke:C.pink,weight:9}),text("Validated, Digital, and Proxy — one property above and one property up to four fiscal modules in each base, all linked to GTA and containing both forest and cerrado.",{width:fill,height:fixed(165),style:{fontFamily:FONT,fontSize:27,color:C.muted}}),text("Mato Grosso · final model run · 6 October 2026",{width:fill,height:fixed(40),style:{fontFamily:FONT,fontSize:20,color:C.muted}})]),column({width:grow(1),height:fill,gap:0,style:{fill:C.yellow}},[image({dataUrl:dataUrl(path.join(ROOT,"deliverables","04_presentation","assets","template_inspiration","un_page_mato_grosso_cattle.jpg")),width:fill,height:grow(1),fit:"cover",alt:"Cattle production landscape in Mato Grosso"}),text("Photo: UN PAGE · Mato Grosso Goes Green",{width:fill,height:fixed(42),style:{fontFamily:FONT,fontSize:20,color:C.purple,textAlign:"center"}})])]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});}

// Selection table
{const tableData=cases.map(c=>[niceSource(c.input_file_type),isLarge(c)?"> 4 modules":"≤ 4 modules",car2(c.CODIGO_CAR),`${fmt(c.MODULOS_FI)} modules · ${ha(c.area_ha_car)} · ${fmt(c.total_cattle_slaughter,0)} cattle`]);const s=deck.slides.add();s.compose(column({width:fill,height:fill,padding:{x:72,y:42},gap:14,style:{fill:C.white}},[heading("The six examples satisfy the same selection rules","Every row is GTA-linked, contains forest and cerrado, and represents one source × size branch.",2),column({width:fill,height:grow(1),gap:3},[tableRow(["Source base","Size","CAR record","Modules · area · cattle"],true),...tableData.map((r,i)=>tableRow(r,false,i))]),footer(2)]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});}

let page=3;
for(const c of cases){const accent=isLarge(c)?C.green:C.ochre; const branch=isLarge(c)?"Article 68":"Article 67"; const tag=`${niceSource(c.input_file_type)} · ${isLarge(c)?"> 4":"≤ 4"} modules`;
  {const s=deck.slides.add();s.compose(column({width:fill,height:fill,padding:{x:48,y:24},gap:9,style:{fill:C.white}},[heading(`${tag} · property overview`,`${fmt(c.MODULOS_FI)} fiscal modules · GTA direct supplier · ${fmt(c.total_cattle_slaughter,0)} slaughter cattle`,page),grid({width:fill,height:grow(1),columns:[fr(2.15),fr(.85)],columnGap:18},[image({dataUrl:dataUrl(c.satellite_map),width:fill,height:fill,fit:"contain",alt:"CAR property boundary over satellite imagery"}),rows([["Property area",ha(c.area_ha_car)],["Forest formation",ha(c.radam_forest_ha)],["Cerrado formation",ha(c.radam_cerrado_ha)],["Current native vegetation",ha(c.rl_exist_total_ha)],["Baseline liability",ha(c.calc_deficit_total_ha)],["With secondary vegetation",ha(c.calc_deficit_total_with_secondary_ha)]],accent)]),text(`CAR: ${c.CODIGO_CAR}`,{width:fill,height:fixed(30),style:{...label,fontSize:20}}),footer(page)]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});page++;}
  for(const [name,subtitle,path] of [["Legal Reserve vector layers","RADAM, current native vegetation, and secondary vegetation.",c.lr_map],["Temporal vector layers","The 2000 and 2008 cut-offs and post-2008 alternative land use.",c.temporal_map],["APP vector layers","APP extent partitioned into mutually exclusive current and temporal classes.",c.app_map]]){const s=deck.slides.add();s.compose(column({width:fill,height:fill,padding:{x:34,y:18},gap:5,style:{fill:C.white}},[heading(`${tag} · ${name}`,subtitle,page),image({dataUrl:dataUrl(path),width:fill,height:grow(1),fit:"contain",alt:`${name} for ${c.CODIGO_CAR}`}),row({width:fill,height:fixed(42),justify:"between",align:"center"},[text("Class totals close exactly to mapped APP area.",{width:wrap(1250),height:fixed(36),style:{...label,fontSize:20}}),text(String(page).padStart(2,"0"),{width:fixed(60),height:fixed(30),style:{...label,fontSize:20,bold:true,color:C.green,textAlign:"right"}})])]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});page++;}
  {const s=deck.slides.add();const req=isLarge(c)?`IF vegetation 2000 ≥ historical floor → floor; ELSE → Article 12 ceiling`:`MIN(Article 12 ceiling, vegetation in 2008)`;s.compose(column({width:fill,height:fill,padding:{x:82,y:48},gap:18,style:{fill:C.white}},[heading(`${tag} · calculation chain`,`${branch} selects the LR requirement; APP and secondary vegetation remain separate.`,page),grid({width:fill,height:grow(1),columns:[fr(1),fr(1)],rows:[fr(1),fr(1)],columnGap:22,rowGap:16},[formula(`${branch} requirement`,req,ha(c.rl_req_base_ha),accent),formula("Legal Reserve deficit",`${ha(c.rl_req_base_ha)} − ${ha(c.rl_exist_total_ha)}`,ha(c.rl_adj_deficit_ha),accent),formula("LR pathway","Restore = MIN(post-2008 clearing, LR deficit)",`${ha(c.rl_restore_ha)} restore · ${ha(c.rl_compensate_ha)} compensate`,accent),formula("APP restoration","Pre-2008 component after cap + post-2008 APP clearing",ha(c.app_restore_ha),accent)]),row({width:fill,height:fixed(105),gap:24},[text(`BASELINE  ${ha(c.calc_deficit_total_ha)}`,{width:grow(1),height:fixed(65),style:{...title,fontSize:35,color:C.red}}),text(`WITH SECONDARY  ${ha(c.calc_deficit_total_with_secondary_ha)}`,{width:grow(1.4),height:fixed(65),style:{...title,fontSize:32,color:C.green}})]),footer(page)]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});page++;}
}

{const summary=cases.map(c=>[niceSource(c.input_file_type),isLarge(c)?"> 4":"≤ 4",car2(c.CODIGO_CAR),ha(c.calc_deficit_total_ha),ha(c.calc_deficit_total_with_secondary_ha)]);const s=deck.slides.add();s.compose(column({width:fill,height:fill,padding:{x:72,y:42},gap:14,style:{fill:C.white}},[heading("What the six examples make visible","The same calculation structure turns source-specific inputs into comparable results.",page),column({width:fill,height:grow(1),gap:3},[summaryRow(["Source","Size","CAR record","Baseline","With secondary"],true),...summary.map((r,i)=>summaryRow(r,false,i))]),footer(page)]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});}

page++;
{const benchmark=[
  ["Current project","155,547 properties · 69.55 Mha","Modeled in total","Included in 5.31 Mha","14.09 Mha"],
  ["OCF 2019","116,390 records · 64.50 Mha","2.30 Mha","0.505 Mha deficit","8.90 Mha"],
  ["OCF 2024","176,629 active/pending · 62.49 Mha","Included in 4.74 Mha total","Included in 4.74 Mha total","5.54 Mha"],
];const widths=[.8,1.5,1,1.15,1];const s=deck.slides.add();s.compose(column({width:fill,height:fill,padding:{x:66,y:42},gap:16,style:{fill:C.white}},[heading("External benchmarks differ materially","Values are not directly equivalent; population, date, overlap treatment, and legal assumptions differ.",page),column({width:fill,height:grow(1),gap:4},[
row({width:fill,height:fixed(70),padding:{x:14,y:12},gap:12,style:{fill:C.pale}},["Source","Population / area","RL deficit","APP metric","Surplus"].map((x,i)=>text(x,{width:grow(widths[i]),height:fixed(42),style:{...base,fontSize:20,bold:true,color:C.purple}}))),
...benchmark.map((r,j)=>row({width:fill,height:fixed(145),padding:{x:14,y:18},gap:12,align:"center",style:{fill:j%2?C.paper:"#FBFAF6"}},r.map((x,i)=>text(x,{width:grow(widths[i]),height:fixed(90),style:{...base,fontSize:20,bold:i===0,color:i===0?C.purple:C.ink}})))),
text("Project and OCF values use non-equivalent populations, dates, and legal denominators.",{width:fill,height:fixed(52),style:{...base,fontSize:20,bold:true,color:C.red}})]),footer(page)]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});}

page++;
{const s=deck.slides.add();s.compose(column({width:fill,height:fill,padding:{x:78,y:46},gap:24,style:{fill:C.white}},[heading("Benchmark interpretation is conditional","External sources validate scale and distribution; they are not an equality test.",page),column({width:fill,height:grow(1),gap:22},[
text("1  Recompute APP partitions and the 2000–2008 chronology before publication.",{width:fill,height:fixed(80),style:{...base,fontSize:26,bold:true,color:C.purple}}),
text("2  Harmonize CAR status, property type, overlap policy, and reference date.",{width:fill,height:fixed(80),style:{...base,fontSize:26,bold:true,color:C.green}}),
text("3  Compare RL deficit, APP gross deficit, required APP restoration, and surplus separately.",{width:fill,height:fixed(80),style:{...base,fontSize:26,bold:true,color:C.red}}),
text("Sources: OCF Mato Grosso diagnostic (2019); OCF Forest Code Thermometer (2024); SFB/SICAR Rural Environmental Regularization Panel.",{width:fill,height:fixed(95),style:{...base,fontSize:20,color:C.muted}}),
text("Status: final model run dated 06 October 2026; external benchmarks remain non-equivalent.",{width:fill,height:fixed(60),style:{...base,fontSize:22,bold:true,color:C.red}})
]),footer(page)]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});}

const out=path.join(ROOT,"deliverables","04_presentation","01_FOREST_CODE_PROPERTY_EXAMPLES_20261006.pptx");
const previewDir=path.join(ROOT,"qa","presentation","gta_examples"); mkdirSync(previewDir,{recursive:true});
const blob=await PresentationFile.exportPptx(deck); await blob.save(out);
for(let i=0;i<deck.slides.items.length;i++){const png=await deck.slides.items[i].export({format:"png",scale:1});await writeFile(path.join(previewDir,`slide-${String(i+1).padStart(2,"0")}.png`),new Uint8Array(await png.arrayBuffer()));}
const inspection=await deck.inspect({kind:"deck,slide,textbox",include:"id,name,slide,text,textLines,bbox,bboxUnit",maxChars:400000});await writeFile(path.join(previewDir,"inspection.ndjson"),inspection.ndjson,"utf8");console.log(out,deck.slides.items.length);
