import { Presentation, PresentationFile, row, column, grid, text, image, rule, fill, fixed, wrap, grow, fr } from "@oai/artifact-tool";
import { readFileSync, mkdirSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const manifest=path.join(ROOT,"deliverables","04_presentation","assets","gta_examples","gta_example_manifest.json");
const cases=JSON.parse(readFileSync(manifest,"utf8"));
const deck=Presentation.create({slideSize:{width:1920,height:1080}});
const C={ink:"#3D2A87",muted:"#5D716C",paper:"#F3F2F0",green:"#147D72",lime:"#11B8B5",ochre:"#F2C94C",red:"#EC3F6B",white:"#FFFFFF",pale:"#E8E5F3",teal:"#11B8B5",pink:"#EC3F6B",yellow:"#FFE266",purple:"#3D2A87"};
const FONT="Bahnschrift"; const base={fontFamily:FONT,color:C.ink};
const title={...base,fontSize:40,bold:true}; const sub={...base,fontSize:23,color:C.muted}; const label={...base,fontSize:16,color:C.muted}; const value={...base,fontSize:21,bold:true};
const fmt=(v,d=2)=>Number(v??0).toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d}); const ha=v=>`${fmt(v)} ha`;
const dataUrl=p=>`data:image/png;base64,${readFileSync(p).toString("base64")}`;
const niceSource=s=>s==="simcar_validado"?"SIMCAR Validated":s==="simcar_digital"?"SIMCAR Digital":"SIMCAR Proxy";
const isLarge=c=>Number(c.MODULOS_FI)>4;
function footer(page){return row({width:fill,height:fixed(42),justify:"between",align:"center"},[text("Source: final GTA-linked Forest Code mega table · 2026-09-30",{width:wrap(1400),height:fixed(36),style:{...label,fontSize:16}}),text(String(page).padStart(2,"0"),{width:fixed(65),height:fixed(30),style:{...label,fontSize:16,bold:true,color:C.green,textAlign:"right"}})]);}
function heading(t,s,p){return column({width:fill,height:fixed(104),gap:3},[text(t,{name:`title-${p}`,width:fill,height:fixed(52),style:{...title,fontSize:40,color:C.purple}}),text(s,{width:wrap(1700),height:fixed(35),style:{...sub,fontSize:20}}),rule({width:fixed(110),stroke:p%2?C.teal:C.pink,weight:6})]);}
function rows(items,accent){return column({width:fill,height:fill,gap:0},items.map((r,i)=>row({width:fill,height:grow(1),align:"center",padding:{x:16,y:7},style:{fill:i%2?C.paper:"#FBFAF6"}},[text(r[0],{width:grow(1.35),height:fixed(30),style:label}),text(r[1],{width:grow(1),height:fixed(32),style:{...value,color:r[2]||accent,textAlign:"right"}})])));}
function formula(name,expression,result,accent){return column({width:fill,height:grow(1),gap:5,padding:{x:20,y:12},style:{fill:"#FBFAF6"}},[text(name,{width:fill,height:fixed(25),style:{...label,bold:true,color:accent}}),text(expression,{width:fill,height:fixed(32),style:{...base,fontSize:18}}),text(`= ${result}`,{width:fill,height:fixed(35),style:{...value,fontSize:23,color:accent}})]);}

// Cover — image-led split inspired by the supplied fluid-shapes template.
{const s=deck.slides.add();s.compose(row({width:fill,height:fill,style:{fill:C.paper}},[column({width:fixed(950),height:fill,padding:{x:90,y:78},gap:25,style:{fill:C.paper}},[text("FOREST CODE · GTA-LINKED WORKED EXAMPLES",{width:fill,height:fixed(42),style:{fontFamily:FONT,fontSize:19,bold:true,color:C.pink,letterSpacing:1.4}}),text("Six properties.\nThree source bases.\nEvery vector layer visible.",{width:fill,height:fixed(330),style:{fontFamily:FONT,fontSize:66,bold:true,color:C.purple}}),rule({width:fixed(260),stroke:C.pink,weight:9}),text("Validated, Digital, and Proxy — one property above and one property up to four fiscal modules in each base, all linked to GTA and containing both forest and cerrado.",{width:fill,height:fixed(165),style:{fontFamily:FONT,fontSize:27,color:C.muted}}),text("Mato Grosso · Final compliance model · 30 September 2026",{width:fill,height:fixed(40),style:{fontFamily:FONT,fontSize:16,color:C.muted}})]),column({width:grow(1),height:fill,gap:0,style:{fill:C.yellow}},[image({dataUrl:dataUrl(path.join(ROOT,"deliverables","04_presentation","assets","template_inspiration","un_page_mato_grosso_cattle.jpg")),width:fill,height:grow(1),fit:"cover",alt:"Cattle production landscape in Mato Grosso"}),text("Photo: UN PAGE · Mato Grosso Goes Green",{width:fill,height:fixed(42),style:{fontFamily:FONT,fontSize:12,color:C.purple,textAlign:"center"}})])]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});}

// Selection table
{const s=deck.slides.add();s.compose(column({width:fill,height:fill,padding:{x:80,y:48},gap:20,style:{fill:C.white}},[heading("The six examples satisfy the same selection rules","Each case is GTA-linked, has forest and cerrado > 0 ha, and represents one source × size branch.",2),grid({width:fill,height:grow(1),columns:[fr(1),fr(1),fr(1)],columnGap:24},[...['simcar_validado','simcar_digital','simcar_proxy'].map(src=>column({width:fill,height:fill,gap:16},[text(niceSource(src),{width:fill,height:fixed(46),style:{...title,fontSize:30,color:C.green}}),...cases.filter(c=>c.input_file_type===src).map(c=>column({width:fill,height:grow(1),gap:5},[text(isLarge(c)?"> 4 modules":"≤ 4 modules",{width:fill,height:fixed(28),style:{...value,color:isLarge(c)?C.green:C.ochre}}),text(c.CODIGO_CAR,{width:fill,height:fixed(46),style:{...label,fontSize:13}}),text(`${fmt(c.MODULOS_FI)} modules · ${ha(c.area_ha_car)} · ${fmt(c.total_cattle_slaughter,0)} slaughter cattle`,{width:fill,height:fixed(45),style:{...base,fontSize:17}})]))]))]),footer(2)]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});}

let page=3;
for(const c of cases){const accent=isLarge(c)?C.green:C.ochre; const branch=isLarge(c)?"Article 68":"Article 67"; const tag=`${niceSource(c.input_file_type)} · ${isLarge(c)?"> 4":"≤ 4"} modules`;
  {const s=deck.slides.add();s.compose(column({width:fill,height:fill,padding:{x:48,y:24},gap:9,style:{fill:C.white}},[heading(`${tag} · property overview`,`${fmt(c.MODULOS_FI)} fiscal modules · GTA direct supplier · ${fmt(c.total_cattle_slaughter,0)} slaughter cattle`,page),grid({width:fill,height:grow(1),columns:[fr(2.15),fr(.85)],columnGap:18},[image({dataUrl:dataUrl(c.satellite_map),width:fill,height:fill,fit:"contain",alt:"CAR property boundary over satellite imagery"}),rows([["Property area",ha(c.area_ha_car)],["Forest formation",ha(c.radam_forest_ha)],["Cerrado formation",ha(c.radam_cerrado_ha)],["Current native vegetation",ha(c.rl_exist_total_ha)],["Baseline liability",ha(c.calc_deficit_total_ha)],["With secondary vegetation",ha(c.calc_deficit_total_with_secondary_ha)]],accent)]),text(`CAR: ${c.CODIGO_CAR}`,{width:fill,height:fixed(30),style:{...label,fontSize:16}}),footer(page)]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});page++;}
  for(const [name,subtitle,path] of [["Legal Reserve vector layers","RADAM, current native vegetation, and secondary vegetation.",c.lr_map],["Temporal vector layers","The 2000 and 2008 cut-offs and post-2008 alternative land use.",c.temporal_map],["APP vector layers","APP extent, vegetation relevant to APP, and pre-/post-2008 liabilities.",c.app_map]]){const s=deck.slides.add();s.compose(column({width:fill,height:fill,padding:{x:34,y:18},gap:5,style:{fill:C.white}},[heading(`${tag} · ${name}`,subtitle,page),image({dataUrl:dataUrl(path),width:fill,height:grow(1),fit:"contain",alt:`${name} for ${c.CODIGO_CAR}`}),row({width:fill,height:fixed(42),justify:"between",align:"center"},[text("Zero ha = source checked; no intersecting feature.",{width:wrap(1250),height:fixed(36),style:{...label,fontSize:16}}),text(String(page).padStart(2,"0"),{width:fixed(60),height:fixed(30),style:{...label,fontSize:16,bold:true,color:C.green,textAlign:"right"}})])]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});page++;}
  {const s=deck.slides.add();const req=isLarge(c)?`IF vegetation 2000 ≥ historical floor → floor; ELSE → Article 12 ceiling`:`MIN(Article 12 ceiling, vegetation in 2008)`;s.compose(column({width:fill,height:fill,padding:{x:82,y:48},gap:18,style:{fill:C.white}},[heading(`${tag} · calculation chain`,`${branch} selects the LR requirement; APP and secondary vegetation remain separate.`,page),grid({width:fill,height:grow(1),columns:[fr(1),fr(1)],rows:[fr(1),fr(1)],columnGap:22,rowGap:16},[formula(`${branch} requirement`,req,ha(c.rl_req_base_ha),accent),formula("Legal Reserve deficit",`${ha(c.rl_req_base_ha)} − ${ha(c.rl_exist_total_ha)}`,ha(c.rl_adj_deficit_ha),accent),formula("LR pathway","Restore = MIN(post-2008 clearing, LR deficit)",`${ha(c.rl_restore_ha)} restore · ${ha(c.rl_compensate_ha)} compensate`,accent),formula("APP restoration","Pre-2008 component after cap + post-2008 APP clearing",ha(c.app_restore_ha),accent)]),row({width:fill,height:fixed(105),gap:24},[text(`BASELINE  ${ha(c.calc_deficit_total_ha)}`,{width:grow(1),height:fixed(65),style:{...title,fontSize:35,color:C.red}}),text(`WITH SECONDARY  ${ha(c.calc_deficit_total_with_secondary_ha)}`,{width:grow(1.4),height:fixed(65),style:{...title,fontSize:32,color:C.green}})]),footer(page)]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});page++;}
}

{const s=deck.slides.add();s.compose(column({width:fill,height:fill,padding:{x:82,y:48},gap:22,style:{fill:C.white}},[heading("What the six examples make visible","Source-specific vector inputs feed the same legal calculation architecture.",page),grid({width:fill,height:grow(1),columns:[fr(1),fr(1),fr(1)],columnGap:22},['simcar_validado','simcar_digital','simcar_proxy'].map(src=>rows(cases.filter(c=>c.input_file_type===src).flatMap(c=>[[`${isLarge(c)?"> 4":"≤ 4"} modules`,c.CODIGO_CAR.slice(0,19)+"…"],["Baseline",ha(c.calc_deficit_total_ha)],["With secondary",ha(c.calc_deficit_total_with_secondary_ha)]]),src==='simcar_proxy'?C.ochre:C.green))),footer(page)]),{frame:{left:0,top:0,width:1920,height:1080},baseUnit:8});}

const out=path.join(ROOT,"deliverables","04_presentation","01_FOREST_CODE_TWO_PROPERTY_WORKED_EXAMPLES_20260930.pptx");
const previewDir=path.join(ROOT,"qa","presentation","gta_examples"); mkdirSync(previewDir,{recursive:true});
const blob=await PresentationFile.exportPptx(deck); await blob.save(out);
for(let i=0;i<deck.slides.items.length;i++){const png=await deck.slides.items[i].export({format:"png",scale:1});await writeFile(path.join(previewDir,`slide-${String(i+1).padStart(2,"0")}.png`),new Uint8Array(await png.arrayBuffer()));}
const inspection=await deck.inspect({kind:"deck,slide,textbox",include:"id,name,slide,text,textLines,bbox,bboxUnit",maxChars:400000});await writeFile(path.join(previewDir,"inspection.ndjson"),inspection.ndjson,"utf8");console.log(out,deck.slides.items.length);

